window.createAuthorViewer=function(host){
 const T=THREE,D=AUTHOR_DESIGN,renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,logarithmicDepthBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe9edf2);renderer.outputColorSpace=T.SRGBColorSpace;host.append(renderer.domElement);
 const scene=new T.Scene(),root=new T.Group();scene.add(root);scene.add(new T.HemisphereLight(0xffffff,0xb9c2ce,2));const light=new T.DirectionalLight(0xffffff,2.5);light.position.set(-2000,4000,3000);scene.add(light);
 const camera=new T.PerspectiveCamera(38,1,20,18000),target=new T.Vector3(830,1050,-530),meshes=new Map();let az=-.35,el=.18,radius=4400,mode='outside',selected=null,explode=0;
 const colors={white:0xffffff,edge:0xaab5c2,black:0x283544,light:0xfafcff,glass:0xabc6d4,mirror:0xb4c8da,screen:0x32576b,cushion:0xf5f2ec,floor:0xb1b5bd};
 for(const p of D.parts){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p.vertices.flatMap(([x,y,z])=>[x,z,-y]),3));g.setIndex(p.triangles.flat());g.computeVertexNormals();const m=new T.MeshStandardMaterial({color:colors[p.material]||0xdddddd,side:T.DoubleSide,roughness:.7,metalness:p.material==='edge'?.35:0,transparent:p.material==='glass',opacity:p.material==='glass'?.22:1,depthWrite:p.material!=='glass'});const mesh=new T.Mesh(g,m);mesh.name=p.name;mesh.userData=p;root.add(mesh);meshes.set(p.id,mesh);const edges=new T.LineSegments(new T.EdgesGeometry(g,25),new T.LineBasicMaterial({color:0x73808c,transparent:true,opacity:.25}));mesh.add(edges);}
 function visible(p){if(selected)return p.id===selected;if(mode==='frame')return p.group==='frame'||p.group==='fasteners';if(mode==='source')return p.authorGeometry;if(mode==='inside')return !['walls','roof','doors'].includes(p.group);if(mode==='service')return p.group!=='doors'&&p.sourceObject!=='ЗАД';return true;}
 function render(){for(const p of D.parts){const mesh=meshes.get(p.id);mesh.visible=visible(p);const c=p.positionMm.map((v,i)=>v+p.worldSizeMm[i]/2),factor=p.authorGeometry?explode:0;mesh.position.set((c[0]-830)*factor,(c[2]-1100)*factor,-(c[1]-530)*factor);}camera.position.set(target.x+Math.sin(az)*radius*Math.cos(el),target.y+Math.sin(el)*radius,target.z+Math.cos(az)*radius*Math.cos(el));camera.lookAt(target);renderer.render(scene,camera);}
 function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();render();}new ResizeObserver(resize).observe(host);
 let down=null,moved=false;renderer.domElement.onpointerdown=e=>{down=[e.clientX,e.clientY];moved=false;renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointermove=e=>{if(!down)return;const dx=e.clientX-down[0],dy=e.clientY-down[1];if(Math.abs(dx)+Math.abs(dy)>2)moved=true;az-=dx*.006;el=Math.max(-1.3,Math.min(1.5,el+dy*.005));down=[e.clientX,e.clientY];render();};renderer.domElement.onpointerup=e=>{if(!moved){const b=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);const hit=ray.intersectObjects([...meshes.values()].filter(m=>m.visible),false)[0];if(hit)window.showAuthorPart?.(hit.object.userData.id);}down=null;};renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();radius=Math.max(350,Math.min(11000,radius*Math.exp(e.deltaY*.001)));render();},{passive:false});
 const api={scene,root,renderer,camera,meshes,render,setView(v){mode=v;selected=null;target.set(830,1050,-530);radius=4400;az=v==='service'?1.5:-.35;el=v==='top'?1.48:.18;if(v==='top')mode='inside';if(v==='inside'){az=-1;el=.26;}render();},isolate(id){selected=id;const p=D.parts.find(p=>p.id===id);if(!p)return;target.set(p.positionMm[0]+p.worldSizeMm[0]/2,p.positionMm[2]+p.worldSizeMm[2]/2,-p.positionMm[1]-p.worldSizeMm[1]/2);radius=Math.max(450,Math.hypot(...p.worldSizeMm)*1.9);el=.3;az=-.6;render();},explode(v){explode=v;render();}};resize();window.authorViewer=api;return api;
};
