/* Budget v12. One shared source; browser edits are portable via JSON export. */
(()=>{
'use strict';
const b=window.BUDGET10,key='fotobudka-budget-editor-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null?'Уточнити ціну':Number(n).toLocaleString('uk-UA',{maximumFractionDigits:2})+' грн';
let state={rowOverrides:{},orderOverrides:{},manualRows:[],hidden:{},buyNow:{}};
try{state={...state,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{}
// Ignore untouched drafts from the previous editor; retain all edited entries.
state.manualRows=state.manualRows.filter(r=>!(r.name==='Нова позиція'&&!r.amount&&!r.note&&!r.orderId&&!state.rowOverrides[r.id]));
let filter='now',search='';
const save=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{alert('Браузер не дозволив зберегти зміни. Скористайтеся експортом.')}};
const rows=()=>[...b.rows,...state.manualRows].map(r=>({...r,...state.rowOverrides[r.id]}));
const now=r=>r.paymentStatus==='PLANNED'&&!r.owned&&!state.hidden[r.id]&&(state.buyNow[r.id]??r.buyNowDefault)!==false;
const later=r=>r.paymentStatus==='PLANNED'&&!now(r);
function orders(){return b.purchases.orders.map(o=>{
 const override=state.orderOverrides[o.id]||{};
 const edits=b.rows.filter(r=>r.orderId===o.id&&r.actualPriceConfirmed).reduce((sum,r)=>{
  const x=state.rowOverrides[r.id];return sum+(x&&x.unitPrice!=null?(Number(x.unitPrice)*(Number(x.qty)||1)-(Number(r.unitPrice)||0)*r.qty):0);
 },0);
 return {...o,...override,goodsSubtotal:Number(o.goodsSubtotal)+edits};
})}
const orderTotal=o=>Number(o.goodsSubtotal||0)+Number(o.shipping||0)+Number(o.fees||0);
function totals(){const list=rows(),all=orders();let spent=0,shipping=0,waiting=0,unpaid=0;
 for(const o of all){if(o.paymentStatus==='PAID'){spent+=orderTotal(o);shipping+=Number(o.shipping||0)+Number(o.fees||0);if(!['RECEIVED','NOT_APPLICABLE'].includes(o.deliveryStatus))waiting+=orderTotal(o)}else if(o.paymentStatus==='UNPAID')unpaid+=orderTotal(o)}
 for(const r of list.filter(r=>r.manual&&r.paymentStatus==='PAID')){spent+=Number(r.amount)||0;if(r.deliveryStatus!=='RECEIVED')waiting+=Number(r.amount)||0;}
 const active=list.filter(now),deferred=list.filter(later);return {spent,shipping,waiting,unpaid,need:active.reduce((s,r)=>s+(r.amount||0),unpaid),later:deferred.reduce((s,r)=>s+(r.amount||0),0),unknown:active.filter(r=>r.amount==null).length,laterUnknown:deferred.filter(r=>r.amount==null).length};
}
const link=url=>/^https?:\/\//.test(url||'')?'<a href="'+esc(url)+'" target="_blank" rel="noopener">Магазин ↗</a>':'';
function editor(r){return '<details class="budget-editor"><summary>Змінити позицію</summary><form data-edit="'+esc(r.id)+'"><div class="budget-form-grid"><label class="budget-form-wide">Назва<input name="name" required value="'+esc(r.name)+'"></label><label>Кількість<input name="qty" type="number" min="0.01" step="0.01" required value="'+r.qty+'"></label><label>Ціна за одиницю, грн<input name="price" type="number" min="0" step="0.01" value="'+(r.unitPrice??'')+'" placeholder="Невідома"></label><label>Категорія<input name="category" required value="'+esc(r.category)+'"></label><label>Посилання на товар<input name="url" type="url" value="'+esc(r.url||'')+'"></label><label class="budget-form-wide">Примітка<textarea name="note">'+esc(r.note)+'</textarea></label></div><button>Зберегти</button></form></details>'}
function card(r){const active=now(r);return '<article class="budget-row '+(active?'budget-planned':'budget-deferred')+'"><div class="row-heading"><span class="budget-status">'+(active?'До покупки':'Відкладено')+'</span><strong>'+money(r.amount)+'</strong></div><h3>'+esc(r.name)+'</h3><p class="budget-meta">'+r.qty+' '+esc(r.unit||'шт.')+(r.unitPrice!=null?' × '+money(r.unitPrice):'')+' · '+esc(r.kind||'Оцінка')+'</p><div class="row-actions"><label><input type="checkbox" data-now="'+esc(r.id)+'" '+(active?'checked':'')+'> Купуємо зараз</label>'+link(r.url)+'</div>'+(r.note?'<details class="row-note"><summary>Пояснення</summary><p>'+esc(r.note)+'</p></details>':'')+editor(r)+'</article>'}
function purchase(o){const items=rows().filter(r=>r.orderId===o.id),received=['RECEIVED','NOT_APPLICABLE'].includes(o.deliveryStatus);return '<details class="budget-group order-card"><summary><span><span class="budget-status '+(received?'status-green':'status-amber')+'">'+(o.paymentStatus==='UNPAID'?'Не оплачено':received?'Отримано / оплачено':'Очікуємо доставку')+'</span><br>'+esc(o.seller)+'<small>Замовлення '+esc(o.id)+'</small></span><strong>'+money(orderTotal(o))+'</strong></summary><div class="order-content"><p>Товари '+money(o.goodsSubtotal)+' · доставка '+money(o.shipping||0)+' · комісії '+money(o.fees||0)+'</p><ul class="receipt-items">'+items.filter(r=>!r.includedInOrderSubtotal).map(r=>'<li><span>'+esc(r.name)+'<small>'+r.qty+' '+esc(r.unit||'шт.')+'</small></span><b>'+money(r.amount)+'</b></li>').join('')+'</ul>'+(items.some(r=>r.includedInOrderSubtotal)?'<details><summary>Склад комплекту (ціна вже врахована)</summary><ul>'+items.filter(r=>r.includedInOrderSubtotal).map(r=>'<li>'+esc(r.name)+'</li>').join('')+'</ul></details>':'')+'<p class="budget-meta">'+esc(o.note||'')+'</p><label>Статус отримання <select data-delivery="'+esc(o.id)+'"><option value="RECEIVED" '+(received?'selected':'')+'>Отримано</option><option value="IN_TRANSIT" '+(!received?'selected':'')+'>Ще не отримано</option></select></label><p class="budget-meta">Підтвердження та контактні дані зберігаються локально у власника.</p></div></details>'}
function render(){const t=totals();
 document.getElementById('budget-summary').innerHTML='<div class="budget-kpis clean-kpis"><article class="budget-kpi budget-bought"><h3>Вже витрачено</h3><h2>'+money(t.spent)+'</h2><p>Включно з доставкою та комісіями: '+money(t.shipping)+'</p></article><article class="budget-kpi budget-required"><h3>Ще потрібно зараз</h3><h2>'+money(t.need)+'</h2><p>'+(t.unknown?'Ще '+t.unknown+' позиції без ціни. ':'')+'За вибраними покупками.</p></article><article class="budget-kpi budget-deferred"><h3>Відкладено</h3><h2>'+money(t.later)+'</h2><p>Не входить у покупку зараз.'+(t.laterUnknown?' Ще '+t.laterUnknown+' без ціни.':'')+'</p></article></div><div class="budget-progress"><span>Витрати + поточний план: <b>'+money(t.spent+t.need)+'</b></span><span>Із витраченого очікуємо товарів на <b>'+money(t.waiting)+'</b></span></div><p class="budget-meta">Ціни майбутніх покупок — попередні орієнтири. Невідомі ціни не включені в підсумок. Інструменти вже є.</p><div class="budget-controls"><div class="budget-filters">'+[['now','Купити зараз'],['paid','Наші покупки'],['later','Відкладено'],['all','Увесь план']].map(([id,label])=>'<button data-filter="'+id+'" aria-pressed="'+(filter===id)+'">'+label+'</button>').join('')+'</div><label class="budget-search">Пошук<input type="search" id="budget-search" placeholder="Назва, категорія або магазин" value="'+esc(search)+'"></label></div><div class="budget-actions"><button id="new-budget-row">+ Додати позицію</button><button id="export-budget">Зберегти мої зміни ↓</button><label class="import-budget">Відновити зміни<input id="import-budget" type="file" accept="application/json"></label><span>Редагування зберігаються в цьому браузері.</span></div><div id="new-budget-slot"></div>';
 const match=r=>(r.name+' '+r.category+' '+(r.url||'')).toLocaleLowerCase().includes(search.toLocaleLowerCase());
 const host=document.getElementById('budget-categories');
 if(filter==='paid'){host.innerHTML=orders().filter(o=>!search||(o.seller+' '+o.id+' '+rows().filter(r=>r.orderId===o.id).map(r=>r.name).join(' ')).toLowerCase().includes(search.toLowerCase())).map(purchase).join('');}
 else{const list=rows().filter(r=>r.paymentStatus==='PLANNED'&&match(r)&&(filter==='all'||(filter==='now'?now(r):later(r))));const cats=[...new Set(list.map(r=>r.category))];host.innerHTML=cats.length?cats.map(cat=>{const group=list.filter(r=>r.category===cat);return '<details class="budget-group" '+(search||cats.length<3?'open':'')+'><summary><span>'+esc(cat)+'<small>'+group.length+' позицій'+(group.some(r=>r.amount==null)?' · є невідомі ціни':'')+'</small></span><strong>'+money(group.reduce((s,r)=>s+(r.amount||0),0))+'</strong></summary><div class="budget-group-content">'+group.map(card).join('')+'</div></details>'}).join(''):'<p class="empty-state">Немає позицій за цим запитом.</p>';}
 bind();
}
function download(name,value){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function bind(){
 document.querySelectorAll('[data-filter]').forEach(el=>el.onclick=()=>{filter=el.dataset.filter;render()});
 document.getElementById('budget-search').oninput=e=>{const pos=e.target.selectionStart;search=e.target.value;render();const input=document.getElementById('budget-search');input.focus();try{input.setSelectionRange(pos,pos)}catch{}};
 document.querySelectorAll('[data-now]').forEach(el=>el.onchange=()=>{state.buyNow[el.dataset.now]=el.checked;delete state.hidden[el.dataset.now];save();render()});
 document.querySelectorAll('[data-delivery]').forEach(el=>el.onchange=()=>{state.orderOverrides[el.dataset.delivery]={...state.orderOverrides[el.dataset.delivery],deliveryStatus:el.value};save();render()});
 document.querySelectorAll('[data-edit]').forEach(form=>form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),id=form.dataset.edit,price=f.get('price')===''?null:Number(f.get('price')),qty=Number(f.get('qty'));state.rowOverrides[id]={...state.rowOverrides[id],name:f.get('name'),category:f.get('category'),url:f.get('url'),note:f.get('note'),qty,unitPrice:price,amount:price==null?null:Math.round(price*qty*100)/100};save();render()});
 document.getElementById('export-budget').onclick=()=>download('prototype-1-budget-changes.json',{version:1,exportedAt:new Date().toISOString(),editor:state,totals:totals()});
 document.getElementById('import-budget').onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(x.version!==1||!x.editor||!Array.isArray(x.editor.manualRows)||['rowOverrides','orderOverrides','hidden','buyNow'].some(k=>!x.editor[k]||typeof x.editor[k]!=='object'))throw Error();state=x.editor;save();render()}catch{alert('Не вдалося прочитати файл. Виберіть експорт цього кошторису.')}};
 document.getElementById('new-budget-row').onclick=()=>{document.getElementById('new-budget-slot').innerHTML='<form id="new-budget-form" class="new-budget-form"><label>Назва нової позиції<input name="name" required placeholder="Наприклад: кріплення монітора"></label><button>Додати</button><button type="button" id="cancel-budget-add">Скасувати</button></form>';document.getElementById('cancel-budget-add').onclick=()=>render();document.getElementById('new-budget-form').onsubmit=e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();if(!name)return;state.manualRows.push({id:'manual-'+Date.now(),manual:true,name,category:'Додані позиції',qty:1,unit:'шт.',unitPrice:null,amount:null,paymentStatus:'PLANNED',deliveryStatus:'NOT_ORDERED',buyNowDefault:true});save();filter='now';search=name;render()}};
}
window.prototypeBudget={totals,rows,orders};render();
})();
