const d=AUTHOR_DESIGN,esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;'),mm=n=>n.toLocaleString('uk-UA',{maximumFractionDigits:2}),viewer=createAuthorViewer(document.getElementById('viewport'));let selected=null;
const select=document.getElementById('part-select');for(const p of d.parts)select.insertAdjacentHTML('beforeend',`<option value="${p.id}">${p.id} · ${esc(p.name)}</option>`);
window.showAuthorPart=id=>{const p=d.parts.find(p=>p.id===id);if(!p)return;selected=id;select.value=id;document.getElementById('part-info').innerHTML=`<p><span class="pill">${p.authorGeometry?'ВАША ДЕТАЛЬ':'ДОДАНО'}</span></p><h3>${esc(p.name)}</h3><strong>Dimensions X / Y / Z</strong><p>${p.dimensionsMm.map(mm).join(' × ')} мм</p><strong>Положення нижнього світового кута</strong><p>${p.positionMm.map(mm).join(' / ')} мм</p><p>${esc(p.status)}</p>${p.fabrication?`<a href="drawings/revision-09/01-all-dsp.svg" target="_blank">Аркуш деталі →</a>`:''}`;};select.onchange=()=>showAuthorPart(select.value);document.getElementById('isolate').onclick=()=>selected&&viewer.isolate(selected);document.getElementById('explode').oninput=e=>viewer.explode(+e.target.value);
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{viewer.setView(b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));});
function page(){let id=location.hash.slice(1)||'model';if(id==='references')id='model';if(!['model','drawings','equipment','decisions','budget','presentation'].includes(id))id='model';document.querySelectorAll('section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+id));if(id==='model')viewer.render();}addEventListener('hashchange',page);page();
document.getElementById('panel-list').innerHTML='<table><tr><th>Деталь</th><th>Назва у Blender</th><th>Dimensions, мм</th><th>Креслення</th></tr>'+d.parts.filter(p=>p.fabrication).map(p=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${p.dimensionsMm.map(mm).join(' × ')}</td><td><a href="drawings/revision-09/01-all-dsp.svg" target="_blank">Відкрити</a></td></tr>`).join('')+'</table>';
const equipment=d.parts.filter(p=>p.group==='equipment'&&/Canon|DNP|Brother|EcoFlow|Мініпк|Nayax|TBD45|Godox/.test(p.name));document.getElementById('equipment-list').innerHTML=equipment.map(p=>`<article class="equipment"><div><h3>${esc(p.name)}</h3><p>${p.dimensionsMm.map(mm).join(' × ')} мм · монтажний габарит</p></div><div><p>Положення показане у 3D. Перевірка сервісних зазорів і кріплення ще потрібна.</p><button data-part="${p.id}">Показати деталь</button></div></article>`).join('');document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{location.hash='model';showAuthorPart(b.dataset.part);viewer.isolate(b.dataset.part);});

const issues=[['Авторські розміри','72 об’єкти перенесено з оновленого файла без зміни Dimensions. Камера, ліфт і термінал у вихідному файлі мають умовні габарити; перевірити розміри реального обладнання перед монтажем.'],['ДСП і передній вузол','Дверцята: 8,87 мм. Похила консоль: габарит 15,86 мм. Передня деталь має кишені й глибину 162,28 мм — це не товщина плити.'],['Принтери й видача','Обидва принтери стоять на авторській полиці. Потрібно опрацювати лотки від їхніх виходів до авторських кишень: A4 зліва, фото по центру.'],['Проводка','Показано маршрути камери, термінала, сканера, принтерів і живлення, додано муфту. Роз’єми, інтерфейс Nayax, довжини та рухому ділянку кабелю перевіряє автор електроніки.']];document.getElementById('issues').innerHTML=issues.map(([t,s])=>'<article class="issue"><h3>'+t+'</h3><p>'+s+'</p></article>').join('');
const b=BUDGET09;document.getElementById('budget-summary').innerHTML='<article class="issue"><h3>Порахована частина: '+mm(b.knownSubtotal)+' грн</h3><p>Це попередній підсумок, а не остаточна ціна готової кабінки. Робота майстра й непрораховані матеріали додаються окремо.</p></article>';
document.getElementById('budget-categories').innerHTML=b.categories.map(c=>'<article class="issue"><h3>'+esc(c.name)+' — '+mm(c.amount)+' грн</h3><p>'+esc(c.quantity)+' · '+esc(c.note)+'</p>'+(c.url?'<a href="'+c.url+'" target="_blank" rel="noopener">Джерело ціни · '+c.date+'</a>':'')+(c.rows?'<details><summary>Позиції категорії</summary><table><tr><th>Позиція</th><th>Кількість</th><th>Сума</th></tr>'+c.rows.map(r=>'<tr><td><a target="_blank" rel="noopener" href="'+(r.options?.[0]?.url||'#')+'">'+esc(r.name)+'</a></td><td>'+r.qty+'</td><td>'+mm((r.options?.[0]?.unitPrice||0)*r.qty)+' грн</td></tr>').join('')+'</table></details>':'')+'</article>').join('')+'<h3>Ще не включено</h3><ul>'+b.excluded.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>';window.dashboardReady=true;