const d=AUTHOR_DESIGN,esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;'),mm=n=>n===null?'Очікуємо ціну':n.toLocaleString('uk-UA',{maximumFractionDigits:2}),viewer=createAuthorViewer(document.getElementById('viewport'));let selected=null;
const select=document.getElementById('part-select');for(const p of d.parts)select.insertAdjacentHTML('beforeend',`<option value="${p.id}">${p.id} · ${esc(p.name)}</option>`);
window.showAuthorPart=id=>{const p=d.parts.find(p=>p.id===id);if(!p)return;selected=id;select.value=id;document.getElementById('part-info').innerHTML=`<p><span class="pill">${p.authorGeometry?'ВАША ДЕТАЛЬ':'ДОДАНО'}</span></p><h3>${esc(p.name)}</h3><strong>Розміри X / Y / Z</strong><p>${p.dimensionsMm.map(mm).join(' × ')} мм</p><strong>Положення нижнього світового кута</strong><p>${p.positionMm.map(mm).join(' / ')} мм</p><p>${esc(p.status)}</p>${p.fabrication?`<a href="../drawings/revision-10/01-all-dsp.svg" target="_blank">Аркуш деталі →</a>`:''}`;};select.onchange=()=>showAuthorPart(select.value);document.getElementById('isolate').onclick=()=>selected&&viewer.isolate(selected);document.getElementById('explode').oninput=e=>viewer.explode(+e.target.value);
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{viewer.setView(b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));});
function page(){let id=location.hash.slice(1)||'model';if(['references','presentation'].includes(id))id='model';if(id==='equipment')id='budget';if(!['model','drawings','equipment','decisions','budget','profit'].includes(id))id='model';document.querySelectorAll('section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+id));if(id==='model')viewer.render();requestAnimationFrame(()=>window.scrollTo(0,0));}addEventListener('hashchange',page);page();
document.getElementById('panel-list').innerHTML='<table><tr><th>Деталь</th><th>Назва у Blender</th><th>Розміри, мм</th><th>Креслення</th></tr>'+d.parts.filter(p=>p.fabrication).map(p=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${p.dimensionsMm.map(mm).join(' × ')}</td><td><a href="../drawings/revision-10/01-all-dsp.svg" target="_blank">Відкрити</a></td></tr>`).join('')+'</table>';
const issues=[['Модуль камери: P2, CNCPROM замовлено','P2: TBD45-700, DM556, Arduino Nano, два HURON NPN NO через PC817/EL817; XL7015 36→12 В. CNCPROM замовлено на 9 587 грн; оплата й отримання не підтверджені. Підготовку БЖ виконуємо окремо. Окрема 3D-модель оновлена; інтеграція в авторську кабінку ще не виконана.'],['Вхід 600 мм','Актуальний виріз у ДСП перед: 600 мм між X = −436 та +164 мм. Рифлений лист автора: 600×1000 мм. Нові назви та геометрія перенесені з файла о 13:44.'],['Сканер у верхньому вирізі','Brother DS-740D встановлено за верхнім вирізом передньої ДСП, над кишенею. Потрібно перевірити на реальному сканері напрям подачі та виходу A4: автоматичне падіння документа в кишеню ще не підтверджене.'],['Авторські розміри','73 об’єкти перенесено з оновленого файла без зміни Розміри. Камера, ліфт і термінал у вихідному файлі мають умовні габарити; перевірити розміри реального обладнання перед монтажем.'],['ДСП і передній вузол','Дверцята: 16 мм. Похила консоль: габарит 15,86 мм. Передня деталь має кишені й глибину 200,58 мм — це не товщина плити.'],['Принтери й видача','Куплено Citizen CY-02. Геометрія попереднього фотопринтера ще не оновлена; посадку Citizen на авторській полиці необхідно перевірити. Потрібно опрацювати лотки від їхніх виходів до авторських кишень: A4 зліва, фото по центру.'],['Проводка','Показано маршрути камери, термінала, сканера, принтерів і живлення, додано муфту. Роз’єми, інтерфейс Nayax, довжини та рухому ділянку кабелю перевіряє автор електроніки.']];document.getElementById('issues').innerHTML=issues.map(([t,s])=>'<article class="issue"><h3>'+t+'</h3><p>'+s+'</p></article>').join('');


issues[0]=['Модуль камери: P2, комплект CNCPROM отримано','Основний комплект TBD45-700, DM556, двигун, кронштейн, муфта, кабелеукладач, два HURON і кріплення оплачено й отримано. Електроніка P2 ще не випробувана: перевірити перетворювач, опторозв’язку, X2, прошивку та утримання каретки без живлення.'];
document.getElementById('issues').innerHTML=issues.map(([t,s])=>'<article class="issue"><h3>'+t+'</h3><p>'+s+'</p></article>').join('');
const b=BUDGET10,editorKey='fotobudka-budget-editor-v1';
let editor={rowOverrides:{},orderOverrides:{},manualRows:[],hidden:{},buyNow:{}};
try{const saved=JSON.parse(localStorage.getItem(editorKey)||'{}');if(saved&&typeof saved==='object')editor={...editor,...saved};}catch{}
// Do not keep an untouched zero-value draft created by an accidental click.
editor.manualRows=(editor.manualRows||[]).filter(row=>!(row.name==='Нова позиція'&&Number(row.unitPrice||0)===0&&!row.note&&!row.orderId&&!row.seller));
const saveEditor=()=>localStorage.setItem(editorKey,JSON.stringify(editor));
const baseOrders=Object.fromEntries(b.purchases.orders.map(order=>[order.id,order]));
const rowsNow=()=>[...b.rows,...editor.manualRows].map(row=>({...row,...editor.rowOverrides[row.id]})).filter(row=>!editor.hidden[row.id]);
const ordersNow=()=>Object.fromEntries(Object.entries(baseOrders).map(([id,order])=>[id,{...order,...editor.orderOverrides[id]}]));
const buyNow=r=>r.paymentStatus==='PLANNED'&&!r.owned&&(typeof editor.buyNow[r.id]==='boolean'?editor.buyNow[r.id]:r.buyNowDefault!==false);
const statusOf=r=>r.paymentStatus==='PAID'?(r.deliveryStatus==='RECEIVED'?'received':r.deliveryStatus==='NOT_APPLICABLE'?'service':'paid-wait'):r.paymentStatus==='UNPAID'?'unpaid':buyNow(r)?'planned':'deferred';
const statusLabel=r=>({received:'✓ Отримано',service:'✓ Послуга оплачена','paid-wait':'⏳ Оплачено, але не отримано',unpaid:'○ Замовлено, не оплачено',planned:'! Ще треба купити',deferred:'Пізніше'})[statusOf(r)];
const options=(values,current)=>values.map(([value,label])=>'<option value="'+value+'" '+(value===current?'selected':'')+'>'+label+'</option>').join('');
function editForm(r){const order=ordersNow()[r.orderId]||{};return '<details class="budget-editor"><summary>Редагувати</summary><form data-budget-edit="'+esc(r.id)+'"><div class="budget-form-grid">'+
 '<label>Оплата<select name="paymentStatus">'+options([['PLANNED','Планується'],['UNPAID','Не оплачено'],['PAID','Оплачено']],r.paymentStatus)+'</select></label>'+
 '<label>Доставка<select name="deliveryStatus">'+options([['NOT_ORDERED','Не замовлено'],['ORDERED','Замовлено'],['IN_TRANSIT','В дорозі / не отримано'],['RECEIVED','Отримано'],['NOT_APPLICABLE','Не застосовується']],r.deliveryStatus)+'</select></label>'+
 '<label>Фактична ціна за одиницю<input name="unitPrice" type="number" step="0.01" value="'+(r.unitPrice??'')+'"></label><label>Кількість<input name="qty" type="number" step="0.01" value="'+(r.qty??1)+'"></label>'+ 
 '<label>Доставка замовлення<input name="shipping" type="number" step="0.01" value="'+(order.shipping??0)+'"></label><label>Комісії замовлення<input name="fees" type="number" step="0.01" value="'+(order.fees??0)+'"></label>'+ 
 '<label>Замовлення №<input name="orderId" value="'+esc(r.orderId||'')+'"></label><label>ТТН<input name="ttn" value="'+esc(order.ttn||'')+'"></label>'+ 
 '<label>Продавець<input name="seller" value="'+esc(order.seller||'')+'"></label><label>Дата<input name="date" value="'+esc(r.date||order.orderDate||'')+'"></label>'+ 
 '<label>Категорія<input name="category" value="'+esc(r.category||'')+'"></label><label class="budget-form-wide">Примітка<textarea name="note">'+esc(r.note||'')+'</textarea></label></div><div class="budget-actions"><button type="submit">Зберегти</button><button type="button" data-budget-delete="'+esc(r.id)+'">'+(r.manual?'Видалити':'Приховати локально')+'</button></div></form></details>'}
function purchaseDetail(r){const order=ordersNow()[r.orderId];if(!order)return '';return '<p class="budget-meta">'+esc(order.seller||'Продавець не вказаний')+' · замовлення №'+esc(order.id)+(order.ttn?' · ТТН '+esc(order.ttn):'')+'</p><p class="budget-meta">Доставка '+mm(order.shipping)+' грн · комісії '+mm(order.fees)+' грн</p>'+(order.evidence?'<a href="'+order.evidence+'" target="_blank" rel="noopener">Підтвердження →</a>':'')}
function budgetCard(r){const status=statusOf(r);return '<article class="budget-row budget-'+status+'"><span class="budget-status">'+statusLabel(r)+'</span><h4>'+esc(r.name)+'</h4><p class="budget-price">'+(r.amount===null?'Ціна ще невідома':mm(r.amount)+' грн')+'</p><p class="budget-meta">'+mm(r.qty)+' '+esc(r.unit||'шт.')+(r.amount!==null?' × '+mm(r.unitPrice)+' грн':'')+'</p>'+purchaseDetail(r)+(r.includedInOrderSubtotal?'<p class="budget-meta"><strong>Ціна входить у subtotal замовлення; окремо не розподілена.</strong></p>':'')+(r.technicalStatus?'<p class="budget-verify">? Технічну роль ще перевірити</p>':'')+'<p>'+esc(r.note||'')+'</p>'+(r.paymentStatus==='PLANNED'?'<label class="budget-priority"><input type="checkbox" data-buy-now="'+esc(r.id)+'" '+(buyNow(r)?'checked':'')+'> Купуємо зараз</label>':'')+(r.url?'<p><a href="'+r.url+'" target="_blank" rel="noopener">Джерело →</a></p>':'')+editForm(r)+'</article>'}
function totals(rows){
 const orders=ordersNow(),byOrder={};
 for(const r of rows){if(r.orderId&&r.actualPriceConfirmed)byOrder[r.orderId]=(byOrder[r.orderId]||0)+(Number(r.unitPrice)||0)*(Number(r.qty)||0)}
 let spent=0,logistics=0,waiting=0,unpaid=0;
 for(const order of Object.values(orders)){
  const goods=(byOrder[order.id]??order.goodsSubtotal??0),shipping=Number(order.shipping)||0,fees=Number(order.fees)||0,total=goods+shipping+fees;
  if(order.paymentStatus==='PAID'){spent+=total;logistics+=shipping+fees;if(!['RECEIVED','NOT_APPLICABLE'].includes(order.deliveryStatus))waiting+=total}
  else if(order.paymentStatus==='UNPAID')unpaid+=total;
 }
 for(const r of rows.filter(r=>r.manual&&r.paymentStatus==='PAID')){
  const total=(Number(r.unitPrice)||0)*(Number(r.qty)||0)+(Number(r.shipping)||0)+(Number(r.fees)||0);
  spent+=total;logistics+=(Number(r.shipping)||0)+(Number(r.fees)||0);
  if(!['RECEIVED','NOT_APPLICABLE'].includes(r.deliveryStatus))waiting+=total;
 }
 return {spent,logistics,waiting,unpaid};
}
function auditBlock(){const a=b.electronicsAudit,group=(title,items,cls)=>'<article class="audit-card '+cls+'"><h4>'+title+'</h4><ul>'+items.map(item=>'<li>'+esc(item)+'</li>').join('')+'</ul></article>';return '<details class="budget-group" open><summary>Електроніка — контроль комплектності</summary><p class="budget-warning">'+esc(a.warning)+'</p><div class="electronics-audit">'+group('✓ Куплено / оплачено',a.purchased,'audit-ok')+group('! Ще треба купити',a.missing,'audit-missing')+group('? Треба перевірити',a.verify,'audit-check')+group('Не потрібно',a.notRequired,'audit-off')+'</div></details>'}
function renderBudget(){const rows=rowsNow(),t=totals(rows),selected=rows.filter(buyNow),required=selected.reduce((sum,r)=>sum+(Number(r.amount)||0),0),unknown=selected.filter(r=>r.amount===null).length;document.getElementById('budget-summary').innerHTML='<div class="budget-actions top-actions"><button data-budget-add>Додати позицію</button><button data-budget-reset>Скинути локальні зміни</button><span>Зміни зберігаються лише в цьому браузері.</span></div><div class="budget-kpis">'+
 '<article class="budget-kpi budget-bought"><h3>Фактично витрачено</h3><h2>'+mm(t.spent)+' грн</h2><p>Тільки оплачені товари, послуги, доставка й комісії.</p></article><article class="budget-kpi budget-logistics"><h3>Доставка та комісії</h3><h2>'+mm(t.logistics)+' грн</h2><p>Кожне замовлення враховане один раз.</p></article><article class="budget-kpi budget-paid-wait"><h3>Оплачено, але не отримано</h3><h2>'+mm(t.waiting)+' грн</h2></article><article class="budget-kpi budget-unpaid"><h3>Замовлено, але не оплачено</h3><h2>'+mm(t.unpaid)+' грн</h2></article><article class="budget-kpi budget-required"><h3>Обов’язково до покупки</h3><h2>'+mm(required)+' грн</h2><p>'+selected.length+' активних позицій'+(unknown?' · ще '+unknown+' без ціни':'')+'.</p></article></div>'+ 
 '<div id="budget-add-slot"></div><details class="budget-group purchase-summary"><summary>Усі фактичні покупки <strong>'+mm(t.spent)+' грн</strong></summary><div class="budget-group-content">'+rows.filter(r=>r.paymentStatus!=='PLANNED').map(budgetCard).join('')+'</div></details>'+auditBlock();
 const categories=[...new Set(rows.map(r=>r.category))];document.getElementById('budget-categories').innerHTML=categories.map(name=>{const list=rows.filter(r=>r.category===name),planned=list.filter(r=>r.paymentStatus==='PLANNED'&&buyNow(r)).reduce((s,r)=>s+(r.amount||0),0);return '<details class="budget-group"><summary><span>'+esc(name)+'</span><small>'+list.length+' позицій · активний план '+mm(planned)+' грн</small></summary><div class="budget-group-content">'+list.map(budgetCard).join('')+'</div></details>'}).join('')+'<h3>Як читати кошторис</h3><ul>'+b.notes.map(n=>'<li>'+esc(n)+'</li>').join('')+'</ul>';bindBudget()}
function bindBudget(){document.querySelectorAll('[data-buy-now]').forEach(input=>input.onchange=()=>{editor.buyNow[input.dataset.buyNow]=input.checked;saveEditor();renderBudget()});document.querySelectorAll('[data-budget-edit]').forEach(form=>form.onsubmit=event=>{event.preventDefault();const id=form.dataset.budgetEdit,row=rowsNow().find(r=>r.id===id),fd=new FormData(form),newOrderId=fd.get('orderId')||row.orderId;editor.rowOverrides[id]={paymentStatus:fd.get('paymentStatus'),deliveryStatus:fd.get('deliveryStatus'),unitPrice:Number(fd.get('unitPrice'))||0,qty:Number(fd.get('qty'))||1,amount:(Number(fd.get('unitPrice'))||0)*(Number(fd.get('qty'))||1),orderId:newOrderId,date:fd.get('date'),category:fd.get('category'),note:fd.get('note'),shipping:Number(fd.get('shipping'))||0,fees:Number(fd.get('fees'))||0,ttn:fd.get('ttn'),seller:fd.get('seller')};if(newOrderId)editor.orderOverrides[newOrderId]={paymentStatus:fd.get('paymentStatus'),deliveryStatus:fd.get('deliveryStatus'),shipping:Number(fd.get('shipping'))||0,fees:Number(fd.get('fees'))||0,ttn:fd.get('ttn'),seller:fd.get('seller')};saveEditor();renderBudget()});document.querySelectorAll('[data-budget-delete]').forEach(button=>button.onclick=()=>{const id=button.dataset.budgetDelete;if(editor.manualRows.some(r=>r.id===id))editor.manualRows=editor.manualRows.filter(r=>r.id!==id);else editor.hidden[id]=true;saveEditor();renderBudget()});document.querySelector('[data-budget-reset]').onclick=()=>{if(confirm('Скинути всі локальні зміни кошторису?')){localStorage.removeItem(editorKey);editor={rowOverrides:{},orderOverrides:{},manualRows:[],hidden:{},buyNow:{}};renderBudget()}};document.querySelector('[data-budget-add]').onclick=()=>{const id='manual-'+Date.now();editor.manualRows.push({id,manual:true,name:'Нова позиція',category:'Ручні позиції',qty:1,unit:'шт.',unitPrice:0,amount:0,paymentStatus:'PLANNED',deliveryStatus:'NOT_ORDERED',date:new Date().toISOString().slice(0,10),note:'',buyNowDefault:true});saveEditor();renderBudget()}}
renderBudget();
window.dashboardReady=true;
