const d=AUTHOR_DESIGN,esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;'),mm=n=>n===null?'Очікуємо ціну':n.toLocaleString('uk-UA',{maximumFractionDigits:2}),viewer=createAuthorViewer(document.getElementById('viewport'));let selected=null;
const select=document.getElementById('part-select');for(const p of d.parts)select.insertAdjacentHTML('beforeend',`<option value="${p.id}">${p.id} · ${esc(p.name)}</option>`);
window.showAuthorPart=id=>{const p=d.parts.find(p=>p.id===id);if(!p)return;selected=id;select.value=id;document.getElementById('part-info').innerHTML=`<p><span class="pill">${p.authorGeometry?'ВАША ДЕТАЛЬ':'ДОДАНО'}</span></p><h3>${esc(p.name)}</h3><strong>Розміри X / Y / Z</strong><p>${p.dimensionsMm.map(mm).join(' × ')} мм</p><strong>Положення нижнього світового кута</strong><p>${p.positionMm.map(mm).join(' / ')} мм</p><p>${esc(p.status)}</p>${p.fabrication?`<a href="drawings/revision-10/01-all-dsp.svg" target="_blank">Аркуш деталі →</a>`:''}`;};select.onchange=()=>showAuthorPart(select.value);document.getElementById('isolate').onclick=()=>selected&&viewer.isolate(selected);document.getElementById('explode').oninput=e=>viewer.explode(+e.target.value);
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{viewer.setView(b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));});
function page(){let id=location.hash.slice(1)||'model';if(['references','presentation'].includes(id))id='model';if(id==='equipment')id='budget';if(!['model','drawings','equipment','decisions','budget','profit','camera','handoff'].includes(id))id='model';document.querySelectorAll('section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+id));if(id==='model')viewer.render();requestAnimationFrame(()=>window.scrollTo(0,0));}addEventListener('hashchange',page);page();
document.getElementById('panel-list').innerHTML='<table><tr><th>Деталь</th><th>Назва у Blender</th><th>Розміри, мм</th><th>Креслення</th></tr>'+d.parts.filter(p=>p.fabrication).map(p=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${p.dimensionsMm.map(mm).join(' × ')}</td><td><a href="drawings/revision-10/01-all-dsp.svg" target="_blank">Відкрити</a></td></tr>`).join('')+'</table>';
const issues=[['Модуль камери: P2, CNCPROM замовлено','P2: TBD45-700, DM556, Arduino Nano, два HURON NPN NO через PC817/EL817; XL7015 36→12 В. CNCPROM замовлено на 9 587 грн; оплата й отримання не підтверджені. Підготовку БЖ виконуємо окремо. Окрема 3D-модель оновлена; інтеграція в авторську кабінку ще не виконана.'],['Вхід 600 мм','Актуальний виріз у ДСП перед: 600 мм між X = −436 та +164 мм. Рифлений лист автора: 600×1000 мм. Нові назви та геометрія перенесені з файла о 13:44.'],['Сканер у верхньому вирізі','Brother DS-740D встановлено за верхнім вирізом передньої ДСП, над кишенею. Потрібно перевірити на реальному сканері напрям подачі та виходу A4: автоматичне падіння документа в кишеню ще не підтверджене.'],['Авторські розміри','73 об’єкти перенесено з оновленого файла без зміни Розміри. Камера, ліфт і термінал у вихідному файлі мають умовні габарити; перевірити розміри реального обладнання перед монтажем.'],['ДСП і передній вузол','Дверцята: 16 мм. Похила консоль: габарит 15,86 мм. Передня деталь має кишені й глибину 200,58 мм — це не товщина плити.'],['Принтери й видача','Куплено Citizen CY-02. Геометрія попереднього фотопринтера ще не оновлена; посадку Citizen на авторській полиці необхідно перевірити. Потрібно опрацювати лотки від їхніх виходів до авторських кишень: A4 зліва, фото по центру.'],['Проводка','Показано маршрути камери, термінала, сканера, принтерів і живлення, додано муфту. Роз’єми, інтерфейс Nayax, довжини та рухому ділянку кабелю перевіряє автор електроніки.']];document.getElementById('issues').innerHTML=issues.map(([t,s])=>'<article class="issue"><h3>'+t+'</h3><p>'+s+'</p></article>').join('');


issues[0]=['Модуль камери: P2, комплект CNCPROM отримано','Основний комплект TBD45-700, DM556, двигун, кронштейн, муфта, кабелеукладач, два HURON і кріплення оплачено й отримано. Електроніка P2 ще не випробувана: перевірити перетворювач, опторозв’язку, X2, прошивку та утримання каретки без живлення.'];
document.getElementById('issues').innerHTML=issues.map(([t,s])=>'<article class="issue"><h3>'+t+'</h3><p>'+s+'</p></article>').join('');

window.dashboardReady=true;
