(function(root){
 const defaults={days:30,uptime:95,traffic:100,area:2.5,rentRate:250,minRent:3000,kwh:100,powerRate:10,internet:300,terminalMonthly:500,bankFee:2.5,maintenance:1000,accounting:500,ownerLabor:0,taxMode:'group2',singleTax:1729.4,militaryFixed:864.7,esv:1902.34,group3rate:5,militaryRate:1,waste:5,photoKit:11626.42,photoYield:1400,paperPack:194.75,paperYield:500,tonerPrice:11131,tonerYield:11000,drumPrice:14072,drumYield:75000,investment:0,depositMonths:1,workingCash:10000,services:[{id:'doc',name:'Фото на документи',daily:3,price:150,photos:1,a4:0},{id:'fun',name:'Розважальні фото',daily:3,price:150,photos:2,a4:0},{id:'copy',name:'Копія / друк A4, одна сторона',daily:10,price:5,photos:0,a4:1},{id:'scan',name:'Сканування, одна сторінка',daily:5,price:5,photos:0,a4:0}]};
 const num=(v,min=0,max=1e12)=>Math.max(min,Math.min(max,Number.isFinite(+v)?+v:0));
 function calculate(input){const s={...defaults,...input};for(const k of Object.keys(defaults))if(typeof defaults[k]==='number')s[k]=num(s[k]);s.days=num(s.days,0,31);s.uptime=num(s.uptime,0,100);s.bankFee=num(s.bankFee,0,100);s.traffic=num(s.traffic,0,1000);for(const k of ['group3rate','militaryRate','waste'])s[k]=num(s[k],0,100);
 const effectiveDays=s.days*s.uptime/100,photoUnit=s.photoKit/Math.max(s.photoYield,1),a4Unit=s.paperPack/Math.max(s.paperYield,1)+s.tonerPrice/Math.max(s.tonerYield,1)+s.drumPrice/Math.max(s.drumYield,1);
 const services=(input.services||defaults.services).map(r=>{const quantity=num(r.daily)*effectiveDays*s.traffic/100,revenue=quantity*num(r.price),unitCost=(num(r.photos)*photoUnit+num(r.a4)*a4Unit)*(1+s.waste/100);return {...r,quantity,revenue,unitCost,materials:quantity*unitCost}});
 const revenue=services.reduce((a,r)=>a+r.revenue,0),materials=services.reduce((a,r)=>a+r.materials,0),transactions=services.reduce((a,r)=>a+r.quantity,0),rent=Math.max(s.area*s.rentRate,s.minRent),cardFees=revenue*s.bankFee/100;
 const percentTax=s.taxMode==='group3'?(s.group3rate+s.militaryRate)/100:0,singleTax=s.taxMode==='group3'?revenue*s.group3rate/100:s.singleTax,militaryTax=s.taxMode==='group3'?revenue*s.militaryRate/100:s.militaryFixed;
 const overhead=rent+s.kwh*s.powerRate+s.internet+s.terminalMonthly+s.maintenance+s.accounting+s.ownerLabor,taxes=singleTax+militaryTax+s.esv,fixed=overhead+s.esv+(s.taxMode==='group3'?0:s.singleTax+s.militaryFixed),expenses=materials+cardFees+taxes+overhead,net=revenue-expenses;
 const investment=s.investment+rent*s.depositMonths+s.workingCash,contribution=revenue-materials-cardFees-revenue*percentTax,margin=revenue>0?contribution/revenue:0,breakEvenRevenue=margin>0?fixed/margin:null,breakEvenDaily=contribution>0&&effectiveDays>0?fixed/(contribution/transactions)/effectiveDays:null;
 const annualLimit=s.taxMode==='group3'?10091049:7211598;
 return {services,effectiveDays,photoUnit,a4Unit,revenue,materials,cardFees,rent,overhead,singleTax,militaryTax,esv:s.esv,taxes,expenses,net,investment,paybackMonths:net>0?investment/net:null,breakEvenRevenue,breakEvenDaily,annualRevenue:revenue*12,annualLimit,overLimit:revenue*12>annualLimit,yearlyNet:net*12};}
 root.KioskEconomics={defaults,calculate};
})(typeof window==='undefined'?globalThis:window);
