(()=>{const T=THREE,host=document.getElementById('scene'),scene=new T.Scene(),renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe6edf4);host.append(renderer.domElement);const camera=new T.PerspectiveCamera(36,1,1,10000);scene.add(new T.HemisphereLight(0xffffff,0x68819d,2));const light=new T.DirectionalLight(0xffffff,2);light.position.set(-600,1100,700);scene.add(light);let az=.55,el=.12,radius=1800;const target=new T.Vector3(25,450,0),all=[],labels=[];
const mat=c=>new T.MeshStandardMaterial({color:c,roughness:.55,metalness:.25}),blue=mat(0x5686ae),silver=mat(0x9cacba),black=mat(0x222b36),orange=mat(0xd99b4a),green=mat(0x398477),dark=mat(0x151b23);const moving=new T.Group();scene.add(moving);
function part(name,geo,pos,m,parent=scene,note='Проєктний габарит; монтаж уточнюється.'){const mesh=new T.Mesh(geo,m);mesh.position.set(...pos);mesh.userData={name,note};parent.add(mesh);all.push(mesh);return mesh;}
const box=(n,w,h,d,x,y,z,m=blue,parent=scene,note)=>part(n,new T.BoxGeometry(w,h,d),[x,y,z],m,parent,note);
function cyl(n,r,l,x,y,z,m=black,parent=scene,axis='z',note){const o=part(n,new T.CylinderGeometry(r,r,l,32),[x,y,z],m,parent,note);if(axis==='z')o.rotation.x=Math.PI/2;if(axis==='x')o.rotation.z=Math.PI/2;return o;}
function label(s,x,y,z){const el=document.createElement('span');el.className='tag';el.textContent=s;host.append(el);labels.push({el,p:new T.Vector3(x,y,z)});}
// The drive shaft crosses the lower belt pulley. Motor axis is horizontal, not coaxial with vertical travel.
const housing=box('TBD45-700 · напрямна',45,820,45,0,410,0,blue,scene,'Підтверджені 45×45 мм, довжина напрямної 820 мм. Загальні торцеві габарити та отвори потрібні від CNCPROM.');
for(const x of [-15,15])box('Паз профілю · умовне зображення',3,794,1,x,410,23,black);
for(const y of [20,800]){box('Торцева опора модуля',65,40,58,0,y,0,silver);cyl('Шків HTD3M · кроковий Ø22,92 мм',72/(2*Math.PI),15,0,y,1,dark,scene,'x','24 зубці × 3 мм = 72 мм/оберт. Зовнішній діаметр залежить від профілю зуба.');}
for(const z of [-11.46,11.46])box('Ремінь HTD3M, ширина 15 мм',15,780,2,0,410,z,black);
box('Каретка TBD45',104,90,26,0,0,39,blue,moving,'104×90×26 мм з опису продавця; схема різьбових отворів не підтверджена.');
box('Перехідна пластина · алюміній 6 мм',120,110,6,0,0,55,orange,moving,'120×110×6 мм — проєкт. Болти M5 показані умовно, координати свердління тільки після креслення каретки.');
box('L-кронштейн Canon · вертикальна полиця',6,100,65,-35,0,88,orange,moving);box('L-кронштейн Canon · опора',80,6,65,2,-50,88,orange,moving);
const body=box('Canon EOS R50 · вертикальна орієнтація',85.5,116.3,68.8,10,10,95,black,moving,'Габаритний макет R50: 116,3×85,5×68,8 мм, повернуто в портрет. Контур і вісь штативного гнізда схематичні.');box('Хват камери',30,100,20,38,10,126,black,moving);
cyl('RF-S 14–30 PZ · об’єктив',34.8,62,0,15,158,dark,moving);cyl('Передня лінза',26,2,0,15,190,green,moving);cyl('Гвинт камери 1/4–20 · умовне місце',3.175,9,-35,10,97,silver,moving,'x','Не задавати довжину входження у камеру без обміру; застосувати готовий captive screw та захист від провертання.');
for(const x of [-40,40])for(const y of [-30,30])cyl('M5 каретки · позиція для узгодження',4.2,4,x,y,60,black,moving);
box('57BYG250C-8 · NEMA23',75.5,56,56,-128,20,0,black,scene,'56×56×75,5 мм; 3 А, 1,8 Н·м утримання, вал Ø8. Крива момент–швидкість не отримана.');box('Фланець двигуна',5,57,57,-88,20,0,silver);
cyl('Вал двигуна Ø8',4,25,-75,20,0,silver,scene,'x');cyl('Вал TBD45 Ø12',6,35,-39,20,0,silver,scene,'x');
const coupling=cyl('Сильфонна муфта 8×12 · D25 L30',12.5,30,-58,20,0,orange,scene,'x','2,4 Н·м номінально. Посадка у LJZ8 і довжини заходу валів не підтверджені.');for(let i=0;i<6;i++)cyl('Гофра сильфона',13,1,-69+i*4,20,0,silver,scene,'x');
for(const z of [-35,35])box('LJZ8-DS45-57 · оболонка-припущення',65,65,4,-56,20,z,orange);box('Захист муфти · знімний',68,4,76,-56,55,0,orange);
for(const x of [-80,80])box('Опорний профіль 20×40 · проєкт',20,920,40,x,450,-55,silver);
for(const y of [100,410,720]){box('Монтажна поперечина · 6 мм',180,40,6,0,y,-30,orange);for(const x of [-15,15])cyl('Кріплення TBD45 до опори · кандидат M5',4,35,x,y,-20,black,scene,'z');}
box('Механічний HOME · умовний корпус',20,10,7,-48,57,32,green,scene,'Один COM/NC кінцевик. Модель, кріплення й отвори підбирає CNCPROM. Розміри умовні.');box('Важіль HOME · умовний',22,1,5,-40,64,32,silver);box('Натискач кінцевика на каретці · проєкт',20,5,8,-40,-8,32,orange,moving);
for(const y of [5,815])box('Механічний упор · не уловлювач падіння',80,10,65,0,y,0,orange);
box('USB-затискач на рухомій пластині',18,20,15,67,0,65,orange,moving);
box('Опора нерухомого кінця ланцюга',155,8,24,147.5,406,30,orange);
box('Винос опори ланцюга від рами',20,30,85,80,410,-12.5,orange);
box('Опора рухомого кінця ланцюга',100,8,24,95,-4,30,orange,moving);
const chain=new T.Group();scene.add(chain);const links=[];for(let i=0;i<44;i++){const m=new T.Mesh(new T.BoxGeometry(40,14,56),black);chain.add(m);links.push(m);}let cable;const cableMaterial=new T.LineBasicMaterial({color:0x228479});
function updateChain(pos){const startY=410,endY=60+pos,R=35,L=1000,bend=(L-Math.PI*R+startY+endY)/2,a=bend-startY,c=Math.PI*R;function pt(t){let d=t*L;if(d<a)return new T.Vector3(215,startY+d,30);d-=a;if(d<c){const ang=d/R;return new T.Vector3(180+R*Math.cos(ang),bend+R*Math.sin(ang),30);}return new T.Vector3(145,bend-(d-c),30);}for(let i=0;i<links.length;i++){const t=i/(links.length-1);links[i].position.copy(pt(t));const tangent=pt(Math.min(1,t+.001)).sub(pt(Math.max(0,t-.001))).normalize();links[i].quaternion.setFromUnitVectors(new T.Vector3(0,1,0),tangent);}if(cable){scene.remove(cable);cable.geometry.dispose();}const points=[pt(1),new T.Vector3(67,endY,65),new T.Vector3(40,endY+10,98)];cable=new T.Line(new T.BufferGeometry().setFromPoints(points),cableMaterial);scene.add(cable);}
label('700 мм · хід',-175,500,0);label('TBD45 · 820 мм',-165,850,0);label('Ланцюг 25×38 · 1 м · схема',210,1050,30);label('NEMA23 → муфта → шків',-160,-40,0);label('HOME · механічний, 1 шт.',-170,105,20);
const axis=new AxisDemo();window.moduleDemo={axis,scene,all};let cycle=false,seq=[100,500,200,650,100],seqIndex=0,last=performance.now(),completed=0;
const $=id=>document.getElementById(id),message=s=>$('feedback').textContent=s;
$('up').onclick=()=>{cycle=false;if(!axis.move(axis.position+25))message('Спочатку HOME; після аварії — скидання та HOME.');};$('down').onclick=()=>{cycle=false;if(!axis.move(axis.position-25))message('Спочатку HOME; після аварії — скидання та HOME.');};
$('home').onclick=()=>{cycle=false;axis.home();message('Подвійний підхід HOME → від’їзд → повільний підхід → паркування.');};$('position').oninput=e=>{$('target').textContent=e.target.value;cycle=false;if(!axis.move(+e.target.value))message('Спочатку HOME; після аварії — скидання та HOME.');};$('speed').oninput=e=>{axis.maxV=+e.target.value;$('speed-value').textContent=e.target.value;};$('center').onclick=()=>axis.move(350);$('cycle').onclick=()=>{if(!axis.homed)return message('Спочатку HOME.');cycle=true;seqIndex=0;axis.move(seq[0]);};$('stop').onclick=()=>{cycle=false;axis.stop();};$('timeout').onclick=()=>{cycle=false;axis.stop('COMM_TIMEOUT');message('Зупинка з уповільненням; автоматичного спуску немає.');};$('estop').onclick=()=>{cycle=false;axis.estop();message('Демонстрація зупинена. Реальний E-STOP потребує уловлювача/гальма.');};$('reset').onclick=()=>axis.reset();$('photo').onclick=()=>message(axis.photo()?'Симульований знімок; реальна камера не підключена.':'Потрібні HOME, повна зупинка й пауза 400 мс.');
$('transparent').onchange=e=>{housing.material=blue.clone();housing.material.transparent=e.target.checked;housing.material.opacity=e.target.checked?.15:1;housing.material.depthWrite=!e.target.checked;};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{az=b.dataset.view==='front'?0:b.dataset.view==='side'?Math.PI/2:.55;el=.12;radius=1800;});
let down;renderer.domElement.onpointerdown=e=>{down=[e.clientX,e.clientY];renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointermove=e=>{if(!down)return;az+=(e.clientX-down[0])*.006;el=Math.max(-1.2,Math.min(1.2,el+(e.clientY-down[1])*.004));down=[e.clientX,e.clientY];};renderer.domElement.onpointerup=()=>down=null;renderer.domElement.ondblclick=e=>{const r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(all)[0];if(hit)$('selected').textContent=hit.object.userData.name+' — '+hit.object.userData.note;};renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();radius=Math.max(450,Math.min(3500,radius*Math.exp(e.deltaY*.001)));},{passive:false});new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}).observe(host);
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;const count=axis.state==='HOMING'?8:1;for(let i=0;i<count;i++)axis.tick(dt);if(cycle&&axis.state==='HOLD'&&axis.settle>.5){seqIndex++;if(seqIndex===seq.length){seqIndex=0;completed++;}axis.move(seq[seqIndex]);}moving.position.y=60+axis.position;updateChain(axis.position);camera.position.set(target.x+Math.sin(az)*radius*Math.cos(el),target.y+Math.sin(el)*radius,target.z+Math.cos(az)*radius*Math.cos(el));camera.lookAt(target);for(const l of labels){const p=l.p.clone().project(camera);l.el.style.display=$('labels').checked&&p.z<1?'block':'none';l.el.style.left=((p.x+1)*host.clientWidth/2)+'px';l.el.style.top=((-p.y+1)*host.clientHeight/2)+'px';}$('status').textContent='СТАН: '+axis.state+'\nПозиція: '+axis.position.toFixed(1)+' мм\nШвидкість: '+axis.velocity.toFixed(1)+' мм/с\nHOME: '+(axis.homed?'відкалібровано':'невідомо')+'\nУтримання: '+(axis.enabled?'увімкнено':'вимкнено')+'\nПомилка: '+(axis.fault||'немає')+'\nЦиклів: '+completed+' · знімків: '+axis.photographs;renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);window.moduleReady=true;
})();
