import assert from 'node:assert/strict';import '../dashboard/economics10.js';import fs from 'node:fs';
const E=globalThis.KioskEconomics,defaults=structuredClone(E.defaults),near=(a,b)=>assert(Math.abs(a-b)<1e-7);
const zero=E.calculate({...defaults,services:[]});assert.equal(zero.revenue,0);assert.equal(zero.paybackMonths,null);assert.equal(zero.breakEvenDaily,null);near(zero.taxes,4496.44);assert(zero.net<0);
const s={...defaults,days:30,uptime:100,traffic:100,taxMode:'group3',bankFee:2.5,services:[{daily:1,price:100,photos:0,a4:0}]},r=E.calculate(s);near(r.revenue,3000);near(r.singleTax,150);near(r.militaryTax,30);near(r.cardFees,75);near(r.taxes,2082.34);near(r.rent,3000);
near(E.calculate({...s,area:20}).rent,5000);assert(E.calculate({...s,services:[{daily:1000,price:1000}]}).overLimit);
const print=E.calculate({...s,services:[{daily:1,price:100,photos:1,a4:1}]});near(print.materials,30*(11626.42/1400+194.75/500+11131/11000+14072/75000)*1.05);
const negative=E.calculate({...s,days:-5,investment:-1});assert.equal(negative.revenue,0);assert.equal(negative.paybackMonths,null);
const b=JSON.parse(fs.readFileSync('drawings/revision-10/budget.json'));assert.equal(b.unpriced,0);assert(b.rows.every(r=>Number.isFinite(r.unitPrice)&&r.unitPrice>0));near(b.fullTotal,b.rows.reduce((s,r)=>s+Math.round(r.qty*r.unitPrice*100)/100,0)*1.1);assert(b.rows.some(r=>r.name.includes('Elo')));assert(!b.rows.some(r=>r.name.includes('Detaik')));
const {chromium}=await import('file:///C:/Users/BD/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});await page.goto(new URL('../dashboard/index.html#profit',import.meta.url).href);await page.waitForFunction(()=>window.profitReady);const before=await page.locator('#profit-results').innerText();await page.click('#traffic-up');assert.notEqual(await page.locator('#profit-results').innerText(),before);await page.reload();await page.waitForFunction(()=>window.profitReady);assert.equal(await page.locator('[data-field="traffic"]').inputValue(),'120');await page.selectOption('#tax-mode','group3');await page.fill('[data-field="traffic"]','0');assert((await page.locator('#profit-results').innerText()).includes('Не окупається'));await page.click('#profit-reset');assert.equal(await page.locator('[data-field="traffic"]').inputValue(),'100');assert.equal(await page.locator('#tax-mode').inputValue(),'group2');await page.screenshot({path:'drawings/revision-10/check-profit-mobile.png',fullPage:true});await browser.close();console.log('PASS economics: taxes on gross, materials, rent floor, zero demand, limits, budget, UI controls and persistence');
